language: node_js
dist: trusty
node_js:
  - "7"
install:
  - npm install hexo-cli -g
  - npm install
  
script:
  - chmod +x ./deploy.sh
  - git clone --branch v5.1.2 https://github.com/iissnan/hexo-theme-next themes/next 
  - hexo clean
  - hexo g
  - ./deploy.sh > /dev/null

branches:
  only:
    - hexo
cache:
  directories:
    - node_modules