language: node_js
dist: trusty
node_js:
  - "7"
install:
  - npm install hexo-cli -g
  - npm install
  
script:
  - chmod +x ./deploy.sh
  - git clone https://github.com/crafet/hexo-theme-next.git themes/next 
  - hexo clean
  - hexo g
  - bash -x ./deploy.sh;

branches:
  only:
    - hexo
cache:
  directories:
    - node_modules